# Locale
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Editor
export EDITOR='nvim'
export VISUAL='nvim'

# Core paths (not managed by mise)
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/go/bin:$PATH"
export PATH="$HOME/dev/bin:$PATH"
export PATH="$HOME/bin:$PATH"
